easy_admin:
    site_name: '<img src="http://www.bluelioncrossfit.fr/images/g5153.png" />Blue Lion CrossFit'
    entities:
        User:
            class: App\Entity\User
            label: 'Users'
#            app_bundle:
            export_path: '%kernel.root_dir/../var/export/user'
            password_encoding: { algorithm: 'bcrypt', cost: 12 }

            list:
                title: 'Utilisateurs'
                fields: ['id', 'username', 'email']

            form:
                title: 'Ajouter/Modifier Utilisateurs'
                fields:
                    - { type: 'group', label: 'Account Information', icon: 'user', css_class: 'col-sm-12' }
                    - username
                    - email
#                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'plainPassword', type: 'password', label: 'Password'}
                    - roles