#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin